output:
  filename: ""
  column:
    hostAddr:
      name: "ip"
    hostPrefix:
      name: "ipprefix"
    networkAddr:
      name: "network"
    networkPrefix:
      name: "networkprefix"
    broadcastAddr:
      name: "broadcast"
    broadcastPrefix:
      name: "broadcastprefix"
    prefixLen:
      name: "prefixlen"
    subnetmask:
      name: "subnetmask"
    wildcardmask:
      name: "wildcardmask"
    addressNum:
      name: "addressnum"
    hostNum:
      name: "hostnum"
    isPrivate:
      name: "private"
    custom:
      name: "vip"
      fromTheLast: "1"