#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import re
import ipaddress

def main():
    num = len(sys.argv)
    target = []
    for i in range(num-1):
        ip = sys.argv[i+1]
        if not check_format_prefix(ip):
            continue
        target.append(ip)
    cal(target)

def cal(target):
    print("--------------------")
    for v in target:
        i = ipaddress.ip_interface(v)
        print("target:    " + i.with_prefixlen)
        print("network:   " + i.network.with_prefixlen)
        print("broadcast: " + str(i.network.broadcast_address))
        print("lastip:    " + str(i.network.broadcast_address - 1))
        print("addrnum:   " + str(i.network.num_addresses))
        print("--------------------")
        

def check_format_prefix(value):
    prefixRegex = "((25[0-5]|1[0-9]{2}|2[0-4][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|1[0-9]{2}|2[0-4][0-9]|[1-9]?[0-9])(/(3[12]|[1-2]?[0-9]))?"
    if re.fullmatch(prefixRegex, value) or value == "":
        return True
    else:
        return False



if __name__ == "__main__":
    main()
